# Generated by Django 4.2.3 on 2023-07-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=100),
        ),
    ]
